### ISSUE TITLE
block that does not come out of the machine

### ISSUE THREAD

**Issue by Hegary06** [HaydenBelanger/assemblylinemachines#22] opened 2021-12-23 02:12 UTC
(1.18.1)when a grind is done with the simple grinder and there is the first slot of the safe (top left) is already used, the item that comes out of the simple grinder does not fit in the safe and disappears.

**Comment by HaydenBelanger** [comment] 2021-12-23 23:13
Hi there, I've tested this in my build and I'm having trouble reproducing it. I've tried having the Simple Grinder process into a Hopper and a Chest and both lock up the Simple Grinder as intended.

What mod adds the Safe?

**Comment by HaydenBelanger** [comment] 2021-12-25 18:08
I'm closing this for now as I can't diagnose this without more information. Please reply and I will reopen it.

**Closed by HaydenBelanger** 2021-12-25 18:08 UTC
Labels: Bug
